export const CONTENT_IS_LOADED = "CONTENT_IS_LOADED";
export const GET_ALL_CONTENT = "GET_ALL_CONTENT";
export const GET_ALL_USER_CONTENT = "GET_ALL_USER_CONTENT";
export const GET_CONTENT = "GET_CONTENT";
export const RECIPE_STATUS = "RECIPE_STATUS";
